#
# Makefile:  /home/grihabor/projects/ncbi_cxx--22_0_0/blastext/src/blastext/Makefile.blastext_test.app
#
# This file was originally generated by shell script "new_project.sh" (r565247)
# Sun Sep 27 09:13:50 MSK 2020
#

###  BASIC PROJECT SETTINGS
APP = blastext_test
SRC = blastext_test
# OBJ =

LIB = blastext xncbi

# LIB      = blastext xser xhtml xcgi xconnect xutil xncbi

## If you need the C toolkit...
# LIBS     = $(NCBI_C_LIBPATH) -lncbi $(NETWORK_LIBS) $(ORIG_LIBS)
# CPPFLAGS = $(ORIG_CPPFLAGS) $(NCBI_C_INCLUDE)

###  EXAMPLES OF OTHER SETTINGS THAT MIGHT BE OF INTEREST
# PRE_LIBS = $(NCBI_C_LIBPATH) .....
# CFLAGS   = $(FAST_CFLAGS)
# CXXFLAGS = $(FAST_CXXFLAGS)
# LDFLAGS  = $(FAST_LDFLAGS)
